repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
        args: [--maxkb=50]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        types_or: [markdown, yaml]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.2.0"
    hooks:
      - id: ruff
        args: [--fix, --extend-ignore=RUF100]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
        additional_dependencies:
          [matplotlib, pandas-stubs, pytest, types-requests]
