name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, v2]
  schedule:
    - cron: "0 5 * * 1" # every monday at 05:00 UTC
  workflow_dispatch:

jobs:
  build:
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest]

    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Create environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          create-args: python=${{ matrix.python-version }}
          environment-file: environments/tests/env-ci.yml
          post-cleanup: none

      - name: Install OSMnx
        run: |
          pip install -e .
          conda list
          conda info --all

      - name: Run pre-commit checks
        run: SKIP=no-commit-to-branch pre-commit run --all-files

      - name: Test docs
        run: make -C ./docs html SPHINXOPTS="-E -W --keep-going"

      - name: Test code and coverage
        run: pytest --verbose --maxfail=1 --typeguard-packages=osmnx --cov=osmnx --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
